name: CI DevOps

on:
  push:
    branches: [ "main", "master" ]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar flask e coverage
        run: pip install flask coverage

      - name: Rodar testes
        run: python -m coverage run -m unittest -v tests/appTest.py

      - name: Exibir relatório
        run: python -m coverage report

  test-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Teste 2
        run: echo "This job tests something 2"